[package]
name = "lambdaworks-math"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"

[dev-dependencies]
test-case = "2.2.2"
criterion = "0.3"

[[bench]]
name = "benchmark"
harness = false
